services:
  server:
    build:
      context: .
    env_file: .env
    restart: always
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-north-1
        awslogs-group: /voice-ai/server
        awslogs-create-group: "true"

  client:
    build:
      context: ../voice-ai-client
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - server
    restart: always
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-north-1
        awslogs-group: /voice-ai/client
        awslogs-create-group: "true"
